version: '2'
services:
  pruebasjhipster-app:
    image: pruebasjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://pruebasjhipster-mysql:3306/pruebasjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://pruebasjhipster-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://pruebasjhipster-elasticsearch:9200
    ports:
      - 8080:8080
  pruebasjhipster-mysql:
    extends:
      file: mysql.yml
      service: pruebasjhipster-mysql
  pruebasjhipster-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: pruebasjhipster-elasticsearch
